version: '2.12.2'

services:
  server:
    build: 
      dockerfile: ./Dockerfile
    container_name: todo_server
    # volumes:
    #   - ./src/:/app
    command: npm run start:dev
    networks:
      - todo_network
    ports:
      - "3000:3000"
    links:
      - mongo
    restart: always
  mongo:
    image: mongo:6.0.3
    container_name: mongo
    networks:
      - todo_network
    volumes:
      - mongo_vol:/data/db
    restart: always
    ports:
      - "27017:27017"

volumes:
  mongo_vol: ~

networks:
  todo_network:
    driver: bridge
    
  