version: '2.12.2'

services:
  server:
    build: 
      dockerfile: Dockerfile
      context: ./src
    volumes:
      - ./src/:data/src/app
    command: npm run start:dev
    networks:
      - todo_network
    ports:
      - "4000:4000"
    links:
      - mongo
    restart: always
  mongo:
    build: ./mongo
    image: NextJStodo/mongodb
    container_name: mongo
    networks:
      - todo_network
    volumes:
      - mongo_vol: data/db
    restart: always
  volumes:
    mongo_vol: ~

  networks:
    todo_network:
      driver: bridge
    
  